### ISSUE TITLE
No tests exist for this project

### ISSUE THREAD

**Issue by andystaples** [Azure/azure-functions-powershell-library#2]
There should be tests, both E2E and unit tests, that confirm the functionality of the Get-FunctionsMetadata cmdlet, the attributes, and any other features bundled with this repository.

**Comment by Francisco-Gamino** [comment]
Please update build.ps1 script to do the following:

1) Build the modules and place it on a test directory
2) Install Pester
3) Make sure Pester is visible to PowerShell
4) New script (test driver) which invokes Pester pointing to the test directory

**Comment by andystaples** [comment]
Tests added and running on commit.
